package com.test.dbtest.dao.mapper;

import com.test.dbtest.dao.domain.DBTest;
import com.test.dbtest.dao.domain.DBTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DBTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    long countByExample(DBTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int deleteByExample(DBTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int insert(DBTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int insertSelective(DBTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    List<DBTest> selectByExample(DBTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    DBTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DBTest record, @Param("example") DBTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DBTest record, @Param("example") DBTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DBTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DBTest record);
}